# ----------------------------
# WARNING: DEV MODE ONLY
# This Docker Compose file is not made for production
# Please use the appropriate Dockerfile at the project root for production use
# For more information, refer to the documentation or README of the project
# ----------------------------

networks:
  internal:
    name: paastech-api-network

services:
  node:
    image: node:18.16.1-alpine3.18
    container_name: paastech-api-node
    working_dir: /opt
    command: 'npm run start:dev'
    # network is in host mode for dev interoperability
    # this allows for ORM commands to be run from the host machine
    # as the env variables do not need to change from the host to the container
    network_mode: host
    volumes:
      # read-write is necessary for build and use
      - ./:/opt:rw
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  db:
    image: postgres:15.3-alpine3.18
    container_name: paastech-api-db
    networks:
      - internal
    ports:
      # publishing the port for the other container to reach
      - 5432:5432
    volumes:
      - ./.db_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: /usr/local/bin/pg_isready -U api -d paastech
      interval: 5s
      timeout: 10s
      retries: 4
    environment:
      POSTGRES_DB: paastech
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api

  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: paastech-api-mail
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - ./.docker/mailhog.auth:/etc/mailhog.auth:ro
    environment:
      MH_AUTH_FILE: /etc/mailhog.auth
