name: Package app to ghcr

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-image:
    uses: paastech-cloud/.github/.github/workflows/docker.yml@main
    with:
      dockerfile: Dockerfile
      context: .
      image_name: api
